### ISSUE TITLE
Auto-convert recursively into subfolders?

### ISSUE THREAD

**Issue by markkindred** [dan-da/py2php#4]
Is recognizing subfolders in which the python code resides then recursively entering and converting py code found within something that I will see when I use this converter?

**Comment by dan-da** [comment]
The php script translate_python_to_php will find all python files in a given directory and translate to php.  It does not recurse at present.

It is a very simple script, and should be straight-forward to add sub-directory recrusion.  If you add that functionality, please submit a pull request.

otherwise, i will keep this issue open and may add it later when I have some free time.

**Comment by markkindred** [comment]
Thanks! Due to a fully loaded docket, it's unlikely I can add the functionality, but I will try!

**Comment by dan-da** [comment]
I added a script build_all_py.php to build recursively in f340e9135021cc5ac9593b2f07dc7210daa0d6da.

It's very basic and only works on linux/unix for now.   maybe can improve it later.
